version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sentimentv1
    depends_on:
      - db
    command: sh -c "until pg_isready -h db -p 5432; do echo Waiting for PostgreSQL...; sleep 2; done; uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentimentv1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/res/database.sql:/docker-entrypoint-initdb.d/database.sql:ro

volumes:
  pgdata:
